"""A closed ticket as a timeline: everything that happened on it, in order.

Built from the raw OTRS articles, fetched again. Each article becomes one entry,
classified by who wrote it and how:

    customer   -- the customer writing in (email, portal, phone logged as such)
    reply      -- one of our staff writing to the customer
    note       -- one of our staff writing internally (not visible to the customer)
    queue      -- the ticket arriving in a queue: OTRS's "New Ticket in Your
                  Queue" notification, reduced to the queue it names

Everything else generated by OTRS is dropped: the feedback-job articles (From
set to the literal "Customer") and any other system article that is not a
queue notification.

Text is cleaned the way search_text is, but per article: the quoted history
goes (cleaner.py -- every reply quotes the one before, and a thread would
otherwise repeat itself fifteen times), then signatures, disclaimers, links and
greetings (search_text.build). What is left is what each person actually wrote.

The queue path comes from the queue entries alone, so it is exact wherever
OTRS recorded the arrivals. Deterministic throughout: no model reads anything
here. This is the input for the step that explains a ticket's journey.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Callable

from ole5.intake.cleaner import clean as split_body
from ole5.intake.search_text import Boilerplate, build as clean_text

CLEAN_VER = "timeline-v3"

# One article's text is cut here. A pasted log or a long list should not crowd
# the rest of the ticket out of what the model reads.
TEXT_CAP = 2000

_NOTIFY_SUBJECT = re.compile(r"New Ticket in Your Queue", re.I)
_NOTIFY_BODY = re.compile(r"has been assigned to your department", re.I)
_QUEUE_LINE = re.compile(r"^\s*Queue:\s*(.+?)\s*$", re.M | re.I)
_GREETING_QUEUE = re.compile(r"^\s*Hello\s+(.+?)\s+Team\s*,", re.M | re.I)


@dataclass
class Timeline:
    entries: list[dict] = field(default_factory=list)
    queue_path: list[str] = field(default_factory=list)
    article_count: int = 0
    notification_count: int = 0
    noise_count: int = 0
    empty_count: int = 0          # written, but nothing left once cleaned
    dropped: list[dict] = field(default_factory=list)   # those, for checking; not stored


def _sender(article: dict) -> tuple[str | None, str | None]:
    """(name, address) from a From header."""
    raw = (article.get("From") or "").strip()
    if "<" in raw and ">" in raw:
        name = raw[: raw.index("<")].strip().strip('"') or None
        address = raw[raw.index("<") + 1: raw.index(">")].strip().lower() or None
        return name, address
    return (None, raw.lower() or None)


def queue_of(article: dict) -> str | None:
    """The queue a notification names, or None if this is not one."""
    subject = article.get("Subject") or ""
    body = article.get("Body") or ""
    if not (_NOTIFY_SUBJECT.search(subject) or _NOTIFY_BODY.search(body)):
        return None
    m = _QUEUE_LINE.search(body) or _GREETING_QUEUE.search(body)
    return m.group(1).strip() if m else None


def kind_of(article: dict) -> str | None:
    """customer / reply / note / queue, or None for noise to drop."""
    if queue_of(article):
        return "queue"
    if (article.get("From") or "").strip() == "Customer":
        return None                       # the feedback job
    sender_type = (article.get("SenderType") or "").lower()
    if sender_type == "system":
        return None
    if sender_type == "customer":
        return "customer"
    visible = str(article.get("IsVisibleForCustomer", "1")) != "0"
    return "reply" if visible else "note"


def _drop_own_name(text: str, name: str | None) -> str:
    """Remove lines made only of the sender's own name -- the signature
    "Hajar" under "Best regards", which the shared rules cannot know is a name.
    Known per article, since OTRS gives the sender's display name."""
    words = {w.casefold() for w in re.findall(r"\w+", name or "")}
    if not words:
        return text
    kept = []
    for line in text.split("\n"):
        tokens = [w.casefold() for w in re.findall(r"\w+", line)]
        if tokens and len(tokens) <= 4 and all(t in words for t in tokens):
            continue
        kept.append(line)
    return re.sub(r"\n{3,}", "\n\n", "\n".join(kept)).strip()


def path(queues: list[str]) -> list[str]:
    """Repeats in a row collapsed: notified twice about one queue is one stay."""
    route: list[str] = []
    for q in queues:
        if q and (not route or route[-1] != q):
            route.append(q)
    return route


def build(articles: list[dict],
          boilerplate_for: Callable[[str | None], Boilerplate]) -> Timeline:
    """The timeline of one ticket from its raw OTRS articles.

    boilerplate_for(address) gives the learned lines to remove for a sender;
    the caller loads the table once rather than once per article.
    """
    def order(a: dict) -> tuple:
        n = a.get("ArticleNumber")
        return (0, int(n)) if str(n or "").isdigit() else (1, str(a.get("ArticleID")))

    tl = Timeline(article_count=len(articles))
    queues: list[str] = []
    first_message = True
    for a in sorted(articles, key=order):
        kind = kind_of(a)
        if kind is None:
            tl.noise_count += 1
            continue
        name, address = _sender(a)
        entry = {
            "no": a.get("ArticleNumber"),
            "at": a.get("CreateTime") or a.get("Created"),
            "kind": kind,
            "from": name or address,
        }
        if kind == "queue":
            q = queue_of(a)
            queues.append(q)
            tl.notification_count += 1
            entry["queue"] = q
        else:
            body = a.get("Body") or ""
            if first_message:
                # The opening message keeps its forwards: a cover note saying
                # "see below" above the real problem is common, and cutting at
                # the first forward would keep only the cover note. Cleaned
                # exactly as search_text is.
                source = body
                first_message = False
            else:
                # Every later reply quotes the one before; only what this
                # person wrote is kept, or a thread repeats itself.
                source = split_body(body).clean or body
            text = clean_text(source, boilerplate_for(address), sender=address)
            text = _drop_own_name(text, name)
            if not text.strip() and kind == "customer":
                # Learned boilerplate is lines a sender repeats. For a customer
                # a repeated one-word reply can be the message itself --
                # "Approved" -- so a customer message emptied only by learned
                # lines is kept, cleaned by the fixed rules alone.
                text = _drop_own_name(clean_text(source, Boilerplate(), sender=address), name)
            if not text.strip():
                tl.empty_count += 1       # "thanks" and a signature
                tl.dropped.append({"no": entry["no"], "kind": kind, "from": entry["from"],
                                   "subject": (a.get("Subject") or "").strip(),
                                   "before": source.strip()})
                continue
            if len(text) > TEXT_CAP:
                text = text[:TEXT_CAP] + " […]"
            entry["subject"] = (a.get("Subject") or "").strip()
            entry["text"] = text
        tl.entries.append(entry)
    tl.queue_path = path(queues)
    return tl


def render(ticket: dict, entries: list[dict], queue_path: list[str],
           names: bool = True) -> str:
    """The timeline as plain text, one block per entry.

    names=False leaves out who wrote each message. A model told not to name
    people still copies a name it can see, so the journey step is not shown
    them at all; the role (CUSTOMER, INTERNAL NOTE, ...) is what it needs.
    """
    head = [
        f"Ticket {ticket.get('ticket_number')}: {ticket.get('title') or ''}".strip(),
        f"Final queue: {ticket.get('queue') or '-'}   Type: {ticket.get('type') or '-'}   "
        f"SubType: {ticket.get('subtype') or '-'}",
        f"Queue path recorded by OTRS: {' -> '.join(queue_path) if queue_path else 'none recorded'}",
        "",
    ]
    labels = {"customer": "CUSTOMER", "reply": "REPLY TO CUSTOMER",
              "note": "INTERNAL NOTE", "queue": "ARRIVED IN QUEUE"}
    body = []
    for e in entries:
        who = f" ({e['from']})" if names and e.get("from") and e["kind"] != "queue" else ""
        top = f"[{e.get('no')}] {e.get('at') or ''}  {labels[e['kind']]}{who}"
        if e["kind"] == "queue":
            body.append(f"{top}: {e.get('queue')}")
            continue
        body.append(top)
        if e.get("subject"):
            body.append(f"Subject: {e['subject']}")
        body.append(e.get("text") or "(no text)")
        body.append("")
    return "\n".join(head + body).strip() + "\n"
